package com.database;
// Generated Mar 1, 2018 1:28:15 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userlikse generated by hbm2java
 */
@Entity
@Table(name="userlikse"
    ,catalog="twitter01"
)
public class Userlikse  implements java.io.Serializable {


     private Integer id;
     private Posttelegram posttelegram;
     private Integer idUser;
     private Boolean likes;

    public Userlikse() {
    }

    public Userlikse(Posttelegram posttelegram, Integer idUser, Boolean likes) {
       this.posttelegram = posttelegram;
       this.idUser = idUser;
       this.likes = likes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_post")
    public Posttelegram getPosttelegram() {
        return this.posttelegram;
    }
    
    public void setPosttelegram(Posttelegram posttelegram) {
        this.posttelegram = posttelegram;
    }

    
    @Column(name="id_user")
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="likes")
    public Boolean getLikes() {
        return this.likes;
    }
    
    public void setLikes(Boolean likes) {
        this.likes = likes;
    }




}


